---
# tasks file for nginx-role
- name: Install epel-release
  tags: nginx
  become: true
  ansible.builtin.yum:
    name: epel-release
    update_cache: true
    state: present
- name: Install nginx
  tags: nginx
  become: true
  ansible.builtin.yum:
    name: nginx
    state: present
  notify: start nginx
